### ISSUE TITLE
(Android) Couldn't expand RemoteViews for: StatusBarNotification

### ISSUE THREAD

**Issue by jamsch** [tanguyantoine/react-native-music-control#148]
# Description

I'm running this on a production app and two Huawei devices running Android 5.1 both seem to crash when this is used. Not sure if anything can be done about this but just thought I'd post the crash log.

```
android.app.RemoteServiceException: Bad notification posted from package com.xxxxxxx.app: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xxxxxxx.app user=UserHandle{0} id=0 tag=MusicControl score=0 key=0|com.xxxxxxx.app|0|MusicControl|10043: Notification(pri=0 contentView=com.xxxxxxx.app/0x109007e vibrate=null sound=null defaults=0x0 flags=0x0 color=0xffffffff category=transport actions=3 vis=PRIVATE))
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5682)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

1. Sample code (provide repo url or sample code)

Will post later

2. Platform ?
   - [ ] iOS
   - [x] Android
   
3. Device
  - [ ] Simulator
  - [x] Real device

Device: HUAWEI LUA-U22 & HUAWEI TAG-L22 both running Android 5.1

**Comment by Kyba1985** [comment]
This issue is related on Android with huawei devices , these devices don't support custom style notification. On my android app i added a check for version android and device to remove style in notification when i create it if is a huawei device and is under android 6.0.

**Comment by moonstruck** [comment]
@Kyba1985 If you share you build procedure / exclusion guide  that'll help others.
Thanks.

**Comment by Kyba1985** [comment]
@moonstruck i fixed this issue on a native android application. In the creation of the notification with the last sdk (27) : 

`
if (Build.MANUFACTURER.toLowerCase(Locale.getDefault()).contains("huawei") && Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {           notificationBuilder.setColor(mNotificationColor).setSmallIcon(R.drawable.ic_notification).setContentIntent(createContentIntent()).setDeleteIntent(createDeleteIntent()).setContentTitle(description.getTitle()).setContentText(description.getSubtitle()).setLargeIcon(art);
        } 
else 
{
notificationBuilder.setStyle(new android.support.v4.media.app.NotificationCompat.MediaStyle().setShowActionsInCompactView(0, 1, 2)// For backwards compatibility with Android L and earlier.
                    .setShowCancelButton(true).setCancelButtonIntent(MediaButtonReceiver.buildMediaButtonPendingIntent(mService, PlaybackStateCompat.ACTION_STOP))  // show only play/pause in compact view
                    .setMediaSession(mSessionToken)).setColor(mNotificationColor).setSmallIcon(R.drawable.ic_notification).setContentIntent(createContentIntent()).setDeleteIntent(createDeleteIntent()).setContentTitle(description.getTitle()).setContentText(description.getSubtitle()).setLargeIcon(art);
        }
`

The important point is setStyle() , must be used only on not huawei devices with android < M

Hope that helps , on my app the fix is tested on half milion users.

**Comment by moonstruck** [comment]
@Kyba1985 Thanks a lot.
I'll try this on my app's next version.

**Comment by anubansal92** [comment]
@tanguyantoine https://github.com/tanguyantoine/react-native-music-control/pull/212
