### ISSUE TITLE
Audio interruption handling not implemented for Android

### ISSUE THREAD

**Issue by parveen-lukha** [tanguyantoine/react-native-music-control#170]
# Description
Audio interruption on Android are not handled. Can anyone help with this?
1. Sample code (provide repo url or sample code)

2. Platform?
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [ ] Real device

**Comment by Guichaguri** [comment]
Audio interruption must be implemented by the module that plays the audio on Android, there's nothing we can do

**Comment by parveen-lukha** [comment]
Hi Guichaguri
Please refer to handleAudioInterruptions function of this module
https://github.com/tanguyantoine/react-native-music-control/blob/master/index.js

It binds NativeMusicControl.observeAudioInterruptions(enable); in case of IOS but in case of Android it just log a console
if (IS_ANDROID) {
      console.log("Audio interruption handling not implemented for Android");
}

**Comment by Guichaguri** [comment]
Yes, that's because the audio interruption events in Android MUST be directly bound to a music player. As this module only implements media buttons, there's nothing we can do.

You should request this to the module that plays the audio, or use another alternative such as `react-native-track-player` which already implements it.

**Comment by tanguyantoine** [comment]
Agree :-)
