### ISSUE TITLE
Unable to set notification icon in Android

### ISSUE THREAD

**Issue by AnilkumarDO** [tanguyantoine/react-native-music-control#287]
Thanks for the great library. 

But, While I tried to set notification icon, It is nothing showing.

I have added images like **my_custom_icon.png** in all drawable directories in android folder.

But, It is not showing in any icon in Notification bar, Only showing play/pause with app title.

    MusicControl.setNowPlaying({
      title: audioTitle,
      artwork: audioImage,
      duration: parseFloat(totalLength), // (Seconds)
      color: 0xFFFFFF, // Notification Color - Android Only
      // date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
      rating: 84, // Android Only (Boolean or Number depending on the type)
      notificationIcon: 'my_custom_icon',
    });

Also I tried in **ComponentDidMount** method to set like
`  MusicControl.setCustomNotificationIcon('my_custom_icon');
`But, Here it is getting crash.

Any suggestions?

I am using this library for my react native project.

**Comment by sfreeman28** [comment]
I'm using ` "react-native-music-control": "0.10.4",` and have it working.
I have png files inside my `drawable` folders (`drawale-xxhdpi` etc).

One thing I noticed is every time you call `setNowPlaying` you need to pass in `notificationIcon: 'my_custom_icon',` otherwise it gets set to the default icon.

I am not setting the `color` property inside setNowPlaying.

**Comment by tanguyantoine** [comment]
May I ask you to add a section into the README?
