### ISSUE TITLE
Is it possible to reverse Jetify this project?

### ISSUE THREAD

**Issue by The0racle** [tanguyantoine/react-native-music-control#342]
# Description

I'm trying to use version `0.12.0` of this repo but my app does not support Andorid X as of yet. I tried reverse jetifying bug to a bunch of errors:

```
3: error: cannot find symbol
import android.support.v4.media.VolumeProviderCompat;

package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle
```

I assume this repo is using android x exclusive libs that do not have a `v4` counterpart, correct?

**Comment by timmywil** [comment]
I don't think this is possible. When I did the PR to migrate to AndroidX, it was because the jetifier didn't work properly. I think this lib is stuck with one or the other. Someone more familiar with Android may be able to modify the code so it can be reserve-jetified, but I'm no Android expert. For now, you might just try downgrading to before it was jetified.

**Comment by bradleyflood** [comment]
Sorry @The0racle Not that I'm aware of.
