### ISSUE TITLE
Android "require()" image support

### ISSUE THREAD

**Issue by jman48** [tanguyantoine/react-native-music-control#43]
# Description
Android version does not support reactjs style require keyword to pass images as the artwork. If you use the require keyword to load an image it will throw IO error as music-control loads from file paths, not drawables. Will then just show the default play icon.

1. Sample code (provide repo url or sample code)
`MusicControl.setNowPlaying({ artwork: require('../images/album.png') });`

2. Platform ?
   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [X] Simulator
  - [X] Real device

**Comment by Guichaguri** [comment]
That would be definitely useful.
@tanguyantoine does the iOS version already supports it?

**Comment by tanguyantoine** [comment]
kind of. In the iOS implementation it seems to rely on local path and you do not need to use the require function : https://github.com/tanguyantoine/react-native-music-control/blob/master/ios/MusicControlManager.m#L251

Could be great to abstract that a lil bit more.

How do you want to call this api

```js
MusicControl.setNowPlaying({ artwork: require('../images/album.png') });
```
or
```js
MusicControl.setNowPlaying({ artwork: 'images/album.png' });
```

The first one is probably clearer in a sense of if it is a string then it is an url otherwise it is a local file.

What do you think ?

**Comment by Guichaguri** [comment]
@tanguyantoine I agree, the `require` one fits better with React Native, as other local image resources are also specified with `require`.

**Comment by tanguyantoine** [comment]
created #46
